/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a8813994759b5eb074ecb4f6f00c6b77)
declare namespace Cloudflare {
	interface Env {
		YJS_VACUUM_INTERVAL_IN_MS: "30000";
		DURABLE_YJSPROVIDER: DurableObjectNamespace<import("./src/index").YjsProvider>;
	}
}
interface Env extends Cloudflare.Env {}
