/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 720a0cd39038affd5d7f537441c8a864)
declare namespace Cloudflare {
	interface Env {
		YJS_VACUUM_INTERVAL_IN_MS: "30000";
		DURABLE_YJSPROVIDER: DurableObjectNamespace<import("./src/index").YjsProvider>;
		R2_YJS_BUCKET: R2Bucket;
	}
}
interface Env extends Cloudflare.Env {}
