/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 376850afb6bc39772d4ccf1a91a296f0)
declare namespace Cloudflare {
	interface Env {
		YJS_VACUUM_INTERVAL_IN_MS: "30000";
		DURABLE_YJSPROVIDER: DurableObjectNamespace<import("./src/index").YjsProvider>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "YJS_VACUUM_INTERVAL_IN_MS">> {}
}
